---
title: "Lab 1 ATMS 748"
author: "Jack Tarricone"
date: "2/8/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2) 
library(dplyr) 
library(lubridate) 
library(chron)
```


```{r}
# read in csv and make room for colnames
hmp_csv_data <-read.csv("/Users/jacktarricone/atms_748/data-code/hmp_data/CSV_21490.SlowResponse_2022_01_18_1732.dat",
                        header = FALSE)
head(hmp_csv_data) # check

# read in ascii for information provided in the header
hmp_ascii_data <-read.table("/Users/jacktarricone/atms_748/data-code/hmp_data/CSV_21490.SlowResponse_2022_01_18_1732.dat")

# rename columns using information in the ascii header
colnames(hmp_csv_data) <- c("year","day","hour_min","sec","BattV_Min","PTemp_C","RH","AirTC_Avg")
head(hmp_csv_data) # check, looks good
tail(hmp_csv_data)

# add in observations column
obs <-seq(1,9921,1)
hmp_csv_data <-cbind(hmp_csv_data,obs) #bind to data frame

# add in month column
month <-rep(2,9921) # only 2 because it's all in feb
hmp_csv_data <-cbind(month, hmp_csv_data) # bind

# create date col
date <-mdy(paste0(hmp_csv_data$month,"-",hmp_csv_data$day,"-",hmp_csv_data$year))
hmp_csv_data$date <-date # data to big dataframe

#format time and paste, assuming all second values are 00
time <- sprintf("%04d", as.numeric(as.character(hmp_csv_data$hour_min)))
hmp_csv_data$time <-times(gsub("(..)(..)", "\\1:\\2:00", time))

# combine into one date and time columb using lubridate
hmp_csv_data$date_time <- ymd_hms(paste(hmp_csv_data$date, hmp_csv_data$time))
head(hmp_csv_data)

# test plot using obs number before date/time formatting
theme_set(theme_light(11)) # set theme for plotting

```

## Temperature

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
