---
title: "Lab 1 ATMS 748"
author: "Jack Tarricone"
date: "2/8/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2) 
library(dplyr) 
library(lubridate) 
library(chron)
```

# Read in data and format the date and time for plotting

```{r}
# read in csv and make room for colnames
csv_path <-"/Users/jacktarricone/atms_748/data-code/hmp_data/CSV_21490.SlowResponse_2022_01_18_1732.dat"
hmp_csv_data <-read.csv(csv_path,
                        header = FALSE)
head(hmp_csv_data) # check

# read in ascii for information provided in the header
ascii_path <-"/Users/jacktarricone/atms_748/data-code/hmp_data/CSV_21490.SlowResponse_2022_01_18_1732.dat"
hmp_ascii_data <-read.table(ascii_path)

# rename columns using information in the ascii header
colnames(hmp_csv_data) <- c("year","day","hour_min","sec","BattV_Min","PTemp_C","RH","AirTC_Avg")
head(hmp_csv_data) # check, looks good

# add in observations column
obs <-seq(1,9921,1)
hmp_csv_data <-cbind(hmp_csv_data,obs) #bind to data frame

# add in month column
month <-rep(2,9921) # only 2 because it's all in feb
hmp_csv_data <-cbind(month, hmp_csv_data) # bind

# create date col
date <-mdy(paste0(hmp_csv_data$month,"-",hmp_csv_data$day,"-",hmp_csv_data$year))
hmp_csv_data$date <-date # data to big dataframe

#format time and paste, assuming all second values are 00
time <- sprintf("%04d", as.numeric(as.character(hmp_csv_data$hour_min)))
hmp_csv_data$time <-times(gsub("(..)(..)", "\\1:\\2:00", time))

# combine into one date and time columb using lubridate
hmp_csv_data$date_time <- ymd_hms(paste(hmp_csv_data$date, hmp_csv_data$time))
```

# Temperature
```{r}
# test plot using obs number before date/time formatting
theme_set(theme_light(11)) # set theme for plotting
ggplot(hmp_csv_data) +
  geom_line(aes(x = date_time, y = AirTC_Avg)) +
  labs(title = "HMP Air Temperature Time Series Jan 19-25 2022") +
  ylab("Temperature (C)") +
  xlab("Date")
```
\
\
\
\

# RH
```{r}
ggplot(hmp_csv_data) +
  geom_line(aes(x = date_time, y = RH), color = "red") +
  labs(title = "HMP Relative Humidity Time Series Jan 19-25 2022") +
  ylab("RH (%)") +
  xlab("Date")
```

# Battery Level
```{r}
ggplot(hmp_csv_data) +
  geom_line(aes(x = date_time, y = BattV_Min), color = "goldenrod") +
  labs(title = "HMP Battery Level Time Series Jan 19-25 2022") +
  ylab("Volts") +
  xlab("Date")
```